CREATE TABLE [dbo].[Addresses]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Street] NVARCHAR(150) NOT NULL,
	[HouseNumber] NVARCHAR(15) NOT NULL,
	[Appartment] NVARCHAR(15) NULL,
	[City] NVARCHAR(100) NOT NULL,
	[State] NVARCHAR(100) NULL,
	[ZipCode] NVARCHAR(15) NOT NULL,
	[Country] NVARCHAR(100) NULL,
	[IsPrimary] BIT NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT [FK_Adresses_User] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id])
)
