CREATE FUNCTION [dbo].[fnHashPassword]
(
	@password NVARCHAR(25),
	@salt NVARCHAR
)
RETURNS NVARCHAR(MAX)
AS
BEGIN
	RETURN CONVERT(NVARCHAR(MAX), HASHBYTES('SHA2_256', CONCAT(@password, @salt)), 1)
END
